#!/bin/bash

# To avoid committing a giant file, this appends a bunch of data onto the log filename
# provided in argv[1]

COUNTER=0
MAX=1000

FILENAME=$1

if [ -z $FILENAME ]; then
  exit 0
fi

while [ $COUNTER -lt $MAX ]; do
  echo '[2016-04-13T17:37:22,589] 1778154862 INFO  [client-handler-worker-35] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digest calculation message: POST/profilerator/v1/profiles.protodjango-auth-token<DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>rFqV3G_OidcnFrU7YVsHmA<Principal><Token>0cwfvw7-5NtopgtlXgj97wRS_Q6m25Qib3dVRCvASGreOF2RD3HHoHO9uc8FDfPy</Token><Signature>w8QTcZEoes0oJ+L9CgytqvcwlGx1iONXx2cfV+l+p7o=</Signature><AppId>5KD-PXR_bovYufXc6Es0QQ</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>N_iBMhq17IDOIOT64NswYmO2ewM7Ws3IlCubhcDmPefeOF2RD3HHoHO9uc8FDfPy</Principal><Token>0cwfvw7-5NtopgtlXgj97wRS_Q6m25Qib3dVRCvASGreOF2RD3HHoHO9uc8FDfPy</Token><Signature>qf/hH7MdGK9GQuwOU5e/elCuv0Ygaz97YsqruLNKqs0=</Signature><AppId>5KD-PXR_bovYufXc6Es0QQ</AppId></DjangoAuthToken></DjangoAuthTokens>django-body-compressedresdjango-body-encryptedbothdjango-cipher-nameDJANGO1111django-cipher-version1.01jQWn9lqTV35fz4+M+huzNjo0yWqMZlOFoPouW30ZYtQzir+e/JQjobF1FlT53QtL/YK5Hs7ULo3v8X27/gjlaTxg2F0fe/cERcb5SB7aXc=
 at com.django.taas.auth.handler.codec.http.HttpDjangoRequestDecoder.createMessage(HttpDjangoRequestDecoder.java:54) ~[authConsumer.jar:?]
[2016-04-13T17:37:58,359] 1778190632 INFO  [client-handler-worker-30] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match: statedDigest=L5EQLJoa5XbcpR88+t4otvQDP7I=, calcDigest=WZmSfVa0f/wl//EeMkff0Kbcba0=
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
 at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.6.6.Final.jar:?]
v5709a904c4fd1049eec724b0-4727ced9772724aa3da7325db8588f8c-559-com.django.acme.service.message.RefreshMessage-true-false
v570c6206c4afd121cfebf351-f87d6cbf5f8e4425536aeaab9ee7d8e6-967-com.django.acme.service.message.RefreshMessage-true-false
 at com.django.taas.auth.handler.codec.http.HttpDjangoMessageDecoder.decode(HttpDjangoMessageDecoder.java:40) ~[authConsumer.jar:?]
[2016-04-13T17:44:58,025] 1778610298 INFO  [client-handler-worker-47] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match for auth:  URI: /profilerator/v1/profiles.proto AuthTokens: djangoAccount = 2130121846;1447340320, djangoDevice = 0b19c3d4b4c1c7f7104b2f42e81cbc9b, djangoDevice [appid] = django,
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-408-com.django.acme.service.message.RefreshMessage-true-false
 at com.django.taas.auth.handler.codec.http.HttpDjangoMessageDecoder.decode(HttpDjangoMessageDecoder.java:132) ~[authConsumer.jar:?]
w56fff4b02ab586117f929e73-4e9f8a5c1d176425f72457be00d23cd1-7431-com.django.acme.service.message.RefreshMessage-true-false
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-438-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:44:57,046] 1778609319 INFO  [client-handler-worker-28] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digest calculation message: POST/profilerator/v1/profiles.protodjango-auth-token<DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>k_EXbny0pJ28TzMYl7A38Q</Principal><Token>UH6WQRAMYl0bFNA9WWYjE4Mbna8_34Qw0_ii52NHUa_eOF2RD3HHoHO9uc8FDfPy</Token><Signature>2eHrknKBRoJTlY5GQ9bo47zAzgQIp+cHkyoA+GW4ZfA=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>RN7hEgzgy9oliNJpI4mBfB0T3vyIH5kxgR_euIzBXdbeOF2RD3HHoHO9uc8FDfPy</Principal><Token>UH6WQRAMYl0bFNA9WWYjE4Mbna8_34Qw0_ii52NHUa_eOF2RD3HHoHO9uc8FDfPy</Token><Signature>aZjIpB8BgNoDNoXYumt59X8HNNqtPoXicnYB6JVqWW4=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken></DjangoAuthTokens>django-body-compressedresdjango-body-encryptedbothdjango-cipher-nameDJANGO1111django-cipher-version1.0mjeO9hzUkRMdyDJrNDLC4HVz4iTsPJU1kCwfjNFdRF4Pf4FdHjT5AhjHhkPFVNqLuoRq6H/TMIKlPy0AX4438dBeBnETNDfHN8CtnzDC34s=
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-382-com.django.acme.service.message.RefreshMessage-true-false
   "message_retrieve_request": {
w56fff4b02ab586117f929e73-4e9f8a5c1d176425f72457be00d23cd1-7402-com.django.acme.service.message.RefreshMessage-true-false
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-412-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:48:19,450] 1778811723 INFO  [client-handler-worker-17] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match for auth:  URI: /profilerator/v1/profiles.proto AuthTokens: djangoAccount = 2404828619, djangoAccount [appid] = djangosocial, djangoDevice = 451817dd4f0538535246aa94ef0cf332, djangoDevice [appid] = djangosocial,
[2016-04-13T17:48:51,574] 1778843847 WARN  [proxy-handler-worker-7] com.django.taas.auth.handler.RecipientHandler - in messageRecieved inboundChannel was closed ignoring setting of channel ops.[id: 0xa6d73065, /10.102.11.54:44126 => us0101ads-vip001/10.100.51.17:8080] RECEIVED: DefaultHttpResponse(chunked: false) HTTP/1.1 200 OK Pragma: no-cache Cache-Control: no-cache, no-store, max-age=0 Expires: Thu, 01 Jan 1970 00:00:00 GMT Content-Type: application/json;charset=UTF-8 Content-Language: en-US Date: Wed, 13 Apr 2016 17:48:51 GMT Server: us0101ads004 Content-Length: 1186, Connection Id = [id: 0xf6aec924, /156.203.164.127:51995 => /199.83.169.114:8080] RECEIVED: DefaultHttpRequest(chunked: false) POST /sdkStorage/v1/2ae427b1add12d5320ebb2e58fda7a20cecd5cac/SU9TX2lQaG9uZTcsMQ%3D%3D/2.14.2.191690/metric/computed.json HTTP/1.1 Host: ipa.django.me Accept: */* Accept-Encoding: deflate, gzip DjangoMe-TaskId: 18 Django-Cipher-Name: DJANGO1111 Django-Cipher-Version: 1.0 Django-Auth-Token: <DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoSdk</Type><Cipher>DJANGO3333</Cipher><Version>1.0</Version><Principal>Y0yO8Dy7mm5r9o2RMnJXWBYByTSZBRIBLatnT_j4jBi7PexVlRGzPKZZkZwaSYQ1Zj2T15_SFn03pZYsjcjKKXh4ZpKp-Sg2XV0e0KD6aUY</Principal><Token>fTeNsqpYaKNIJgulDBhX3_CfwKZxhrJB4tiAveFOZvlUlOSHx5hLdVDHmiTwXGVP</Token><Expiration>1756146179</Expiration><Signature>MBalULdBnbowE2iKM/q3FaabI6G7wUnj3AZpOYbQTuY=</Signature></DjangoAuthToken></DjangoAuthTokens> Django-Body-Encrypted: both Django-Body-Compressed: res Django-Digest: ru+MfPntG1BjSZ0cgHs8O7lmHIg= Content-Type: application/json X-Forwarded-For: 156.203.164.127 Content-Length: 2907 X-DjangoAuth-Sdk-Urn: urn:django:token:1.0:Django:RoadRiot:236843162{"grp":[],"access":[1,2,3,4]}
v570a4d631b62caf5311f5dab-0b9cff8803de9c719e215c6cedb878bb-242-com.django.acme.service.message.RefreshMessage-true-false
w56f958cb1ce926ee9d7a45e0-c7facde81e5a32522c4c5ca20f438e6e-3831-com.django.acme.service.message.RefreshMessage-true-false
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-343-com.django.acme.service.message.RefreshMessage-true-false
v5707c031d0c1126c6ea9c43d-87554f5dd3ec93f0f5a0fcb0e1414af5-225-com.django.acme.service.message.RefreshMessage-true-false
w5703fa12d0c1126c6e0c6777-86c63a77b4be7f750aa092cd91478519-1344-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:49:29,223] 1778881496 WARN  [proxy-handler-worker-4] com.django.taas.auth.handler.RecipientHandler - in messageRecieved inboundChannel was closed ignoring setting of channel ops.[id: 0x5f00e491, /10.102.11.54:29028 => us0101apf-vip001/10.100.11.22:8080] RECEIVED: DefaultHttpResponse(chunked: false) HTTP/1.1 200 OK X-Protobuf-Schema: v1/UserProfile.proto X-Protobuf-Message: com.django.profilerator.proto.v1.UserProfileResponse Content-Type: application/x-protobuf;charset=UTF-8 Content-Length: 462 Date: Wed, 13 Apr 2016 17:49:28 GMT Server: us0101apf007, Connection Id = [id: 0x00f9b506, /37.211.192.244:9989 => /199.83.169.114:8080] RECEIVED: DefaultHttpRequest(chunked: false) POST /profilerator/v1/profiles.proto HTTP/1.1 Host: profilerator.django.me Accept: */* Accept-Encoding: deflate, gzip DjangoMe-TaskId: 70724 Django-Cipher-Name: DJANGO1111 Django-Cipher-Version: 1.0 Django-Auth-Token: <DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>7DOtne2NvgMQDdeEhud-mw</Principal><Token>nEWAQ6uwibn9ENf-yVeEe4OsEt2cl3pg4YJ7L8G-IWDeOF2RD3HHoHO9uc8FDfPy</Token><Signature>NsXd83ruKsEYvLQpb3kltcsnnKLivQPZOXxPokLYNKk=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>NRpglUIxJzRbvnOZSK_dtP9POCOC2S4vfKSZmEGlwjXeOF2RD3HHoHO9uc8FDfPy</Principal><Token>nEWAQ6uwibn9ENf-yVeEe4OsEt2cl3pg4YJ7L8G-IWDeOF2RD3HHoHO9uc8FDfPy</Token><Signature>z+ofg5cALXh8pI4e13FyZhdUa3PBj430PQ6UlhX2UcU=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken></DjangoAuthTokens> Django-Body-Encrypted: both Django-Body-Compressed: res Django-Digest: hcjOHPrTK16/yJ/ydg+qoZszA1U= Content-Type: application/x-protobuf X-Forwarded-For: 37.211.192.244 Content-Length: 78 X-DjangoAuth-Username: b07ed7f5fb4ee9d970d6a195344c97a7 X-DjangoAuth-AccountId: 2209965260 X-DjangoAuth-AppId: django
[2016-04-13T17:49:39,186] 1778891459 INFO  [client-handler-worker-45] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match: statedDigest=sw8hDnJjIGmrUGmem3wamnZPmWE=, calcDigest=Mig2X+2J/Kc8HijSYww/ch+AsiQ=
v570d04a43da1ee514b1710c7-6c3dc89cfbb014e6ca6835aa7583732e-108-com.django.acme.service.message.RefreshMessage-true-false
 at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[netty-3.6.6.Final.jar:?]
v570acb36fc0fe40ba24029fd-038448a16fb19275d5ebcdd99aa6b211-455-com.django.acme.service.message.RefreshMessage-true-false
w5702638de16664acbfa0549e-1b8e8d697e9aea357f82eecad32c215a-1172-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T18:02:19,505] 1779651778 WARN  [proxy-handler-worker-26] com.django.taas.auth.handler.RecipientHandler - in messageRecieved inboundChannel was closed ignoring setting of channel ops.[id: 0x8476101c, /10.102.11.54:9623 => us0101afe-vip001/10.100.51.15:8080] RECEIVED: DefaultHttpResponse(chunked: false) HTTP/1.1 200 OK Content-Type: application/json Date: Wed, 13 Apr 2016 18:02:19 GMT Server: us0101afe007 Content-Length: 700, Connection Id = [id: 0xceced2f2, /91.107.145.175:62156 => /199.83.169.114:8080] RECEIVED: DefaultHttpRequest(chunked: false) POST /feed/v6/like/296693754532725110 HTTP/1.1 Host: 199.83.169.50 Accept-Encoding: deflate, gzip Accept: application/json DjangoMe-TaskId: 1473 Django-Cipher-Name: DJANGO1111 Django-Cipher-Version: 1.0 Django-Auth-Token: <DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>3wTTDSOH9Hn9edeIC6dy4Q</Principal><Token>wowOKFN6B2Wc3FJnkXey6RMEd8dyohvWhepm2aR-wUjeOF2RD3HHoHO9uc8FDfPy</Token><Signature>F3hWLRKxNGpgtExRPgH0RNqaTXHp6NN3ViXBXNJt30s=</Signature></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>Paz1IuWh36IKvHHyrkuKHWqvwtafeUER-RKaFoRG2hreOF2RD3HHoHO9uc8FDfPy</Principal><Token>wowOKFN6B2Wc3FJnkXey6RMEd8dyohvWhepm2aR-wUjeOF2RD3HHoHO9uc8FDfPy</Token><Signature>qxQwcatGy00Ww7aCr77NeVv+h7GUUvOlb3jDi6tcO3U=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken></DjangoAuthTokens> Django-Body-Encrypted: both Django-Body-Compressed: none Django-Digest: bTA94C7l9EcPLxzFZmMApaYX7+E= Content-Type: application/json X-Forwarded-For: 91.107.145.175 Content-Length: 25 X-DjangoAuth-Username: 483fad6278d8fb08772718ad5c6978d9 X-DjangoAuth-AppId: django X-DjangoAuth-AccountId: 1553629870
w56fe27c7c0c5c785e78b78c8-7a2b594f18ceaf769b00af17d473f982-2965-com.django.acme.service.message.RefreshMessage-true-false
v570acb36fc0fe40ba24029fd-038448a16fb19275d5ebcdd99aa6b211-329-com.django.acme.service.message.RefreshMessage-true-false
w57056fc485e8f79c93b70afb-6bd87092b50e518e41a864fbc9dfc284-3073-com.django.acme.service.message.RefreshMessage-true-false
v570b98a8967f00800f68aedb-735e1879ffc8c7bce02af3283d4c5f30-811-com.django.acme.service.message.RefreshMessage-true-false
w56f95be22d5f7e6883760ba9-c6677f263d4566a08d41dee3848486d7-9285-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T18:03:45,807] 1779738080 INFO  [client-handler-worker-9] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match: statedDigest=lMpRoDaUdfPWNxWPZ08hv2AUUxw=, calcDigest=1rBqq04I9KJp/bICdcC2HO3VJXg=
w570160d72d5f7e6883ca1a65-bf678651f538b058ca59b0fa2d6b4cf1-5917-com.django.acme.service.message.RefreshMessage-true-false
v570395b4696b8b2ae9af6f7a-cfedda87b25e3c695941e552507f9d93-939-com.django.acme.service.message.RefreshMessage-true-false
w56ffe57549021789b9475eba-14ba0e542284eff4d16b41bafa2bfada-3853-com.django.acme.service.message.RefreshMessage-true-false
Apr 13 11:25:47 us0101bac024 access.log  78.95.168.113 - - [13/Apr/2016:18:25:45 +0000] "POST /profilerator/v1/profiles.proto HTTP/1.1" 200 196 B "proxy-handler-worker-6" 31 ms us0101bac024.djangome.gbl 174548296 793b34b129d4707757b6292219305188 -
x56f4a484ce8b6e2cccde1a6b-f599b3b4cc7d61f051a23ee58c51c3ba-14445-com.django.acme.service.message.RefreshMessage-true-false
v5705337173935d34464a5368-7bc5f9890089a80ab6b422a1ef4de0d2-120-com.django.acme.service.message.RefreshMessage-true-false
w570c6206c4afd121cfebf351-f87d6cbf5f8e4425536aeaab9ee7d8e6-1014-com.django.acme.service.message.RefreshMessage-true-false
w5701169e89e88eada96fecc8-ab9a3ea70933a6d092159cdbadf78036-4917-com.django.acme.service.message.RefreshMessage-true-false
w570818e4c4afd121cf37bba9-50d9d98d2d9e57ffde1ac1ddf2522238-1092-com.django.acme.service.message.RefreshMessage-true-false
w570062973d5a209ae7609a23-dc2f2c9a40f01b882689305e3019c6e5-6440-com.django.acme.service.message.RefreshMessage-true-false
w56fefcf801f66b998eb247df-d77fb1371c53657833f874ff560108f6-2361-com.django.acme.service.message.RefreshMessage-true-false
v570c685d73935d3446824308-7c6a0cc2b49be90b40f89947237cdc02-461-com.django.acme.service.message.RefreshMessage-true-false
           {
v5703e861d4bd0a78340e2d66-3dc2182d84df0c799fc7736957e9c7f0-441-com.django.acme.service.message.RefreshMessage-true-false
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4119-com.django.acme.service.message.RefreshMessage-true-false
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4089-com.django.acme.service.message.RefreshMessage-true-false
w570160d72d5f7e6883ca1a65-bf678651f538b058ca59b0fa2d6b4cf1-6178-com.django.acme.service.message.RefreshMessage-true-false
u5709358659bbdd4690640662-b41114c0e4640a746ff3cbf2d8994de9-12-com.django.acme.service.message.RefreshMessage-true-false
v5709aee7689d1f1628cff0a7-5cd32f344b73eecc77e36b75f825ea4a-684-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:29:28,948] 1777681221 INFO  [client-handler-worker-1] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match: statedDigest=Hjdr9qZ26IeHozYwdMpVrgrmE/o=, calcDigest=aXXc4Xj9hSweWI8Kx6ONCVNMb2I=
v570d31d1ea7e840697fe7aed-15b45f3a71a6643693043a72dfed795a-155-com.django.acme.service.message.RefreshMessage-true-false
w570160d72d5f7e6883ca1a65-bf678651f538b058ca59b0fa2d6b4cf1-5676-com.django.acme.service.message.RefreshMessage-true-false
v570d31d1ea7e840697fe7aed-15b45f3a71a6643693043a72dfed795a-132-com.django.acme.service.message.RefreshMessage-true-false
v570aaa6649021789b915d8c3-9a9d4fad3cde34d34889d1ab0b8c2fd6-145-com.django.acme.service.message.RefreshMessage-true-false
w570b8782f1b66fcd8a3ffd0b-232fc99806f0654f6b02df8c32d6a9c4-2501-com.django.acme.service.message.RefreshMessage-true-false
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4286-com.django.acme.service.message.RefreshMessage-true-false
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4252-com.django.acme.service.message.RefreshMessage-true-false
w5701622d2d5f7e6883ca659e-bf678651f538b058ca59b0fa2d6b4cf1-3125-com.django.acme.service.message.RefreshMessage-true-false
w5705232b73868d7c515e09c6-04b313e55ec883f6a9b8edf5b4636ecb-3433-com.django.acme.service.message.RefreshMessage-true-false
u570d25a801f66b998e1b8014-d7cc61256e2078bf5f4468e63a464037-75-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:29:36,557] 1777688830 INFO  [client-handler-worker-23] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digest calculation message: POST/tc2/v2/rr/updatedjango-auth-token<DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>VJ1fiG_QJyBXjAZ8MuRL2A</Principal><Token>xTHAvavBhj6LikQqGInHpedKkSmYbzSgULQzOcF7Qc3eOF2RD3HHoHO9uc8FDfPy</Token><Signature>ck2nML4UuZYJBjC4dhUjj3a4SFS25Rn9NtpwLzow/AU=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>LREIqQWcWMu9vOtlrhrl0lXs_b65_E7rwKairPUbbfjeOF2RD3HHoHO9uc8FDfPy</Principal><Token>xTHAvavBhj6LikQqGInHpedKkSmYbzSgULQzOcF7Qc3eOF2RD3HHoHO9uc8FDfPy</Token><Signature>U2DU6yieJ0nvr+NbIlKJe0i1FK37P+5Vt3hO/SQdXPY=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken></DjangoAuthTokens>django-body-compressednonedjango-body-encryptednonedjango-cipher-nameDJANGO1111django-cipher-version1.0{
       "include_changed_conversation_state": "true"
w570160d72d5f7e6883ca1a65-bf678651f538b058ca59b0fa2d6b4cf1-5848-com.django.acme.service.message.RefreshMessage-true-false
v570d81740e7747c859332799-cf7124f5031070215a060a94f4313805-482-com.django.acme.service.message.RefreshMessage-true-false
v5706d74be16664acbf6139b2-18e29bc909ce30b5025ed579a4b968be-943-com.django.acme.service.message.RefreshMessage-true-false
v570a739dc073c746332d8c6b-1778e600e254e0779b43cb92af2b9ef9-402-com.django.acme.service.message.RefreshMessage-true-false
u570ad22a32df0544166ff41e-1821c1b80e3310e07f0e90bffb666a6f-97-com.django.acme.service.message.RefreshMessage-true-false
v56fa8a13c210d66636d520c0-5cfca35b9325f27ae58dbae103f19077-262-com.django.acme.service.message.RefreshMessage-true-false
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4191-com.django.acme.service.message.RefreshMessage-true-false
 at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90) ~[netty-3.6.6.Final.jar:?]
w570486d76eeba622450cb81b-30a348d3b29763ff1765ffd035684ca6-2182-com.django.acme.service.message.RefreshMessage-true-false
v570a739dc073c746332d8c6b-1778e600e254e0779b43cb92af2b9ef9-367-com.django.acme.service.message.RefreshMessage-true-false
w570486d76eeba622450cb81b-30a348d3b29763ff1765ffd035684ca6-2199-com.django.acme.service.message.RefreshMessage-true-false
w5704c83aea7e840697924197-57d12ebd855de534ef5431fe2c75fef2-7219-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:37:22,589] 1778154862 INFO  [client-handler-worker-35] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match for auth:  URI: /profilerator/v1/profiles.proto AuthTokens: djangoAccount = 370739903, djangoAccount [appid] = djangosocial, djangoDevice = 4fb486d2bddf41c151c29cc6e81ab83d, djangoDevice [appid] = djangosocial,
 at com.django.taas.auth.handler.codec.http.HttpDjangoMessageDecoder.decode(HttpDjangoMessageDecoder.java:132) ~[authConsumer.jar:?]
[2016-04-13T17:37:58,359] 1778190632 INFO  [client-handler-worker-30] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digest calculation message: POST/acme/sync/v1/4252ddf23e2211fae314eddb4fd695eadjango-auth-token<DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>ialGAP6SAKbJtv45oZ8G8w</Principal><Token>mxGpTRKrKpkIPzlGtwMba3HbhI8fNVn0X8o2uu3mjrPeOF2RD3HHoHO9uc8FDfPy</Token><Signature>1F01lzwaKN/UGM2X6sH5wvwX/TVYUhRxsy7/++beZrk=</Signature><AppId>5KD-PXR_bovYufXc6Es0QQ</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>ItvcYsvlxdJX_UkidlDGC4JbOFtFWv38qbTatVJsmhPeOF2RD3HHoHO9uc8FDfPy</Principal><Token>mxGpTRKrKpkIPzlGtwMba3HbhI8fNVn0X8o2uu3mjrPeOF2RD3HHoHO9uc8FDfPy</Token><Signature>QB7C8wLyJ+AIGvASurq/EzoVe93AwbVc6BVzzFEaGOs=</Signature><AppId>5KD-PXR_bovYufXc6Es0QQ</AppId></DjangoAuthToken></DjangoAuthTokens>django-body-compressednonedjango-body-encryptednonedjango-cipher-nameDJANGO1111django-cipher-version1.0�
[2016-04-13T17:38:31,187] 1778223460 INFO  [client-handler-worker-34] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match: statedDigest=HTgOpcaVT9uTZyMLyYSknN25rMA=, calcDigest=nxvGr5y/YsJRP6SyuaSts6be7k0=
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_25]
v5709a904c4fd1049eec724b0-4727ced9772724aa3da7325db8588f8c-560-com.django.acme.service.message.RefreshMessage-true-false
v570c6206c4afd121cfebf351-f87d6cbf5f8e4425536aeaab9ee7d8e6-968-com.django.acme.service.message.RefreshMessage-true-false
 at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.6.6.Final.jar:?]
[2016-04-13T17:44:58,025] 1778610298 INFO  [client-handler-worker-47] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Authentication failed  URI: /profilerator/v1/profiles.proto AuthTokens: djangoAccount = 2130121846;1447340320, djangoDevice = 0b19c3d4b4c1c7f7104b2f42e81cbc9b, djangoDevice [appid] = django,
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-409-com.django.acme.service.message.RefreshMessage-true-false
 at com.django.taas.auth.handler.codec.http.HttpDjangoMessageDecoder.decode(HttpDjangoMessageDecoder.java:40) ~[authConsumer.jar:?]
w56fff4b02ab586117f929e73-4e9f8a5c1d176425f72457be00d23cd1-7432-com.django.acme.service.message.RefreshMessage-true-false
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-439-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:44:57,046] 1778609319 INFO  [client-handler-worker-28] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match for auth:  URI: /profilerator/v1/profiles.proto AuthTokens: djangoAccount = 53507531, djangoAccount [appid] = django, djangoDevice = 76c24eb6854006870e90a202a4e1d377, djangoDevice [appid] = django,
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-383-com.django.acme.service.message.RefreshMessage-true-false
       "start_timestamp": "1460048735421",
w56fff4b02ab586117f929e73-4e9f8a5c1d176425f72457be00d23cd1-7403-com.django.acme.service.message.RefreshMessage-true-false
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-413-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:48:19,450] 1778811723 INFO  [client-handler-worker-17] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Authentication failed  URI: /profilerator/v1/profiles.proto AuthTokens: djangoAccount = 2404828619, djangoAccount [appid] = djangosocial, djangoDevice = 451817dd4f0538535246aa94ef0cf332, djangoDevice [appid] = djangosocial,
[2016-04-13T17:48:51,933] 1778844206 WARN  [proxy-handler-worker-46] com.django.taas.auth.handler.RecipientHandler - in messageRecieved inboundChannel was closed ignoring setting of channel ops.[id: 0x308f3d14, /10.102.11.54:1623 => us0101afc-vip001/10.101.61.6:8080] RECEIVED: DefaultHttpResponse(chunked: false) HTTP/1.1 200 OK Content-Type: application/xml;charset=UTF-8 Content-Length: 800 Date: Wed, 13 Apr 2016 17:48:51 GMT Server: us0101afc033, Connection Id = [id: 0x53addc76, /176.54.103.61:43807 => /199.83.169.114:8080] RECEIVED: DefaultHttpRequest(chunked: false) POST /facilitator/rest/validation/v1/django_validation/62578227a62416aedece897ae335a039 HTTP/1.1 Host: facilitator.django.me Accept: */* Accept-Encoding: deflate, gzip DjangoMe-TaskId: 11 Django-Cipher-Name: DJANGO1111 Django-Cipher-Version: 1.0 Django-Auth-Token: <DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>mPTKju2NbXxq6eWSrfGSqA</Principal><Token>bk7XUz9bfL6S5xkFK69tsc2xHZvsvSj-Zg6Zf_0EQNHeOF2RD3HHoHO9uc8FDfPy</Token><Signature>0bw+CpmaCrywGl6/ev1v0Cp7Puc4l6tptgLv/rAEV7s=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>tZYZb8z_dwVJisOUzzChMqo3BjqiSBGAk1WBQrbjICXeOF2RD3HHoHO9uc8FDfPy</Principal><Token>bk7XUz9bfL6S5xkFK69tsc2xHZvsvSj-Zg6Zf_0EQNHeOF2RD3HHoHO9uc8FDfPy</Token><Signature>W1meNDQAjnxrxx3ElDucn/dVxltWhqUPgYhYgxmKWE0=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken></DjangoAuthTokens> Django-Body-Encrypted: none Django-Body-Compressed: none Django-Digest: PIfpzFzlX+MLerCzOM9jXhWRGf8= Content-Type: text/xml X-Forwarded-For: 176.54.103.61 Content-Length: 2327 X-DjangoAuth-Username: 62578227a62416aedece897ae335a039 X-DjangoAuth-AccountId: 853748772 X-DjangoAuth-AppId: django
v570a4d631b62caf5311f5dab-0b9cff8803de9c719e215c6cedb878bb-243-com.django.acme.service.message.RefreshMessage-true-false
w56f958cb1ce926ee9d7a45e0-c7facde81e5a32522c4c5ca20f438e6e-3832-com.django.acme.service.message.RefreshMessage-true-false
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-344-com.django.acme.service.message.RefreshMessage-true-false
v5707c031d0c1126c6ea9c43d-87554f5dd3ec93f0f5a0fcb0e1414af5-226-com.django.acme.service.message.RefreshMessage-true-false
w5703fa12d0c1126c6e0c6777-86c63a77b4be7f750aa092cd91478519-1345-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:49:29,651] 1778881924 INFO  [client-handler-worker-35] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match: statedDigest=3PNyJeYKRdzRCn5ACywNMNoK/o0=, calcDigest=w47YcD+VvD0wqYWA3A7n5EP3o0w=
[2016-04-13T17:49:39,186] 1778891459 INFO  [client-handler-worker-45] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digest calculation message: POST/profilerator/v1/profiles.protodjango-auth-token<DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>FGp01Ol-Gl0OAb5sLpBZbw</Principal><Token>hUZeW_OqTGXgx93csyCuT3U8i9Jli9jLjHfYrUjtasneOF2RD3HHoHO9uc8FDfPy</Token><Signature>qkdxjc0xI6PqMqOIDHogwjg1ug4eaRg7FE+qgwJqkkM=</Signature><AppId>XmjmeOS0n6DAdG1UZH-IlQ</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>ADt29rUz4daWHWU9D8J7pZUtvnELMbvoJmccWxSeMLTeOF2RD3HHoHO9uc8FDfPy</Principal><Token>hUZeW_OqTGXgx93csyCuT3U8i9Jli9jLjHfYrUjtasneOF2RD3HHoHO9uc8FDfPy</Token><Signature>GUWI7FD39G/hoZ6+O45TbuIo9nPyGRFdvsAlRQ0X7JE=</Signature><AppId>XmjmeOS0n6DAdG1UZH-IlQ</AppId></DjangoAuthToken></DjangoAuthTokens>django-body-compressedresdjango-body-encryptedbothdjango-cipher-nameDJANGO1111django-cipher-version1.023/CYsCCCt1wIp3ulqXHQT5hLasX1Sbfg7zPEXN5d0Ut6hJ7ogrCflW4s69ebGH8EQyx6Oqz1qvfUvyUD9V1j2CARlxibAKZAFlC0p7wS4k=
v570d04a43da1ee514b1710c7-6c3dc89cfbb014e6ca6835aa7583732e-109-com.django.acme.service.message.RefreshMessage-true-false
 at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90) ~[netty-3.6.6.Final.jar:?]
v570acb36fc0fe40ba24029fd-038448a16fb19275d5ebcdd99aa6b211-456-com.django.acme.service.message.RefreshMessage-true-false
w5702638de16664acbfa0549e-1b8e8d697e9aea357f82eecad32c215a-1173-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T18:02:19,589] 1779651862 ERROR [proxy-handler-worker-47] com.django.taas.auth.handler.RecipientHandler - Exception happened while processing request to protected server [id: 0x6468e507, /10.102.11.54:8990 => us0101gc-vip001/10.100.11.121:8080] EXCEPTION: org.jboss.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 26214400 bytes., Connection Id = [id: 0x53def60f, /172.58.153.206:29273 => /199.83.169.114:8080] RECEIVED: DefaultHttpRequest(chunked: false) POST /tc2/v1/message/get HTTP/1.1 Host: tc2.django.me Accept-Encoding: deflate, gzip Accept: application/json DjangoMe-TaskId: 131 Django-Cipher-Name: DJANGO1111 Django-Cipher-Version: 1.0 Django-Auth-Token: <DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>v_4hWPzxm8ldKTNHyN8bVQ</Principal><Token>hMdmXZ12q3HXCq5qAlXjq038jqD48kXbqmDPgBMFnPzeOF2RD3HHoHO9uc8FDfPy</Token><Signature>nZdsPwihAE86Ry8gghzqNUzha2AwdZtktOkz217Eeag=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>lecFgZsWQssUiGCoceYkax9Gz7vuohazHUyJnmqemH7eOF2RD3HHoHO9uc8FDfPy</Principal><Token>hMdmXZ12q3HXCq5qAlXjq038jqD48kXbqmDPgBMFnPzeOF2RD3HHoHO9uc8FDfPy</Token><Signature>SUIizRHYvtBrRkavkDhzDMxcsemXL2e/HOsjYmW0mRI=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken></DjangoAuthTokens> Django-Body-Encrypted: none Django-Body-Compressed: none Django-Digest: qH0Tk/e2AQf2x7YwYXM6PpsgUZs= Content-Type: application/json; charset=utf-8 X-Forwarded-For: 172.58.153.206 Content-Length: 311 X-DjangoAuth-Username: e03f578ba85a5237563d7a9543718d73 X-DjangoAuth-AccountId: 415882389 X-DjangoAuth-AppId: django
w56fe27c7c0c5c785e78b78c8-7a2b594f18ceaf769b00af17d473f982-2967-com.django.acme.service.message.RefreshMessage-true-false
v570acb36fc0fe40ba24029fd-038448a16fb19275d5ebcdd99aa6b211-330-com.django.acme.service.message.RefreshMessage-true-false
w57056fc485e8f79c93b70afb-6bd87092b50e518e41a864fbc9dfc284-3074-com.django.acme.service.message.RefreshMessage-true-false
v570b98a8967f00800f68aedb-735e1879ffc8c7bce02af3283d4c5f30-812-com.django.acme.service.message.RefreshMessage-true-false
w56f95be22d5f7e6883760ba9-c6677f263d4566a08d41dee3848486d7-9286-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T18:03:45,807] 1779738080 INFO  [client-handler-worker-9] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digest calculation message: POST/acme/sync/v1/48cab8da14dad89c2d73194c91a1aefedjango-auth-token<DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>6gRdbIGbYdxDiyov71zYDQ</Principal><Token>wgbx-v1FB2rWo8P_RKiio4FV0rxF216R6IbPHICQbqHeOF2RD3HHoHO9uc8FDfPy</Token><Signature>ZnMwgdnSJLmci65SDoKIh5wOwzC04jN9Dw0CfqhPZN0=</Signature></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>MeOmzWV5hlR44_8xAHjlStkmpT4OrtclKWAjcivy5qjeOF2RD3HHoHO9uc8FDfPy</Principal><Token>wgbx-v1FB2rWo8P_RKiio4FV0rxF216R6IbPHICQbqHeOF2RD3HHoHO9uc8FDfPy</Token><Signature>oHQXju4NrXHBllDVwR8KqQ/o/wRUzO8OjLRALrgqO+Y=</Signature></DjangoAuthToken></DjangoAuthTokens>django-body-compressednonedjango-body-encryptednonedjango-cipher-nameDJANGO1111django-cipher-version1.0�
w570160d72d5f7e6883ca1a65-bf678651f538b058ca59b0fa2d6b4cf1-5918-com.django.acme.service.message.RefreshMessage-true-false
v570395b4696b8b2ae9af6f7a-cfedda87b25e3c695941e552507f9d93-940-com.django.acme.service.message.RefreshMessage-true-false
w56ffe57549021789b9475eba-14ba0e542284eff4d16b41bafa2bfada-3856-com.django.acme.service.message.RefreshMessage-true-false
Apr 13 11:25:47 us0101bac024 access.log  37.37.174.18 - - [13/Apr/2016:18:25:45 +0000] "POST /profilerator/v1/profiles.proto HTTP/1.1" 200 281 B "proxy-handler-worker-22" 33 ms us0101bac024.djangome.gbl 2144854468 a5247f1e1657b749c6d9778c4849b7fe django
x56f4a484ce8b6e2cccde1a6b-f599b3b4cc7d61f051a23ee58c51c3ba-14446-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T18:10:00,696] 1780112969 INFO  [client-handler-worker-19] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match for auth:  URI: /acme/sync/v1/b8d6e5dad4bea5b7cba85ffd0c410ab4 AuthTokens: djangoAccount = 2397026295, djangoAccount [appid] = django, djangoDevice = 7bc5f9890089a80ab6b422a1ef4de0d2, djangoDevice [appid] = django,
w570c6206c4afd121cfebf351-f87d6cbf5f8e4425536aeaab9ee7d8e6-1015-com.django.acme.service.message.RefreshMessage-true-false
w5701169e89e88eada96fecc8-ab9a3ea70933a6d092159cdbadf78036-4919-com.django.acme.service.message.RefreshMessage-true-false
w570818e4c4afd121cf37bba9-50d9d98d2d9e57ffde1ac1ddf2522238-1093-com.django.acme.service.message.RefreshMessage-true-false
w570062973d5a209ae7609a23-dc2f2c9a40f01b882689305e3019c6e5-6441-com.django.acme.service.message.RefreshMessage-true-false
w56fefcf801f66b998eb247df-d77fb1371c53657833f874ff560108f6-2362-com.django.acme.service.message.RefreshMessage-true-false
v570c685d73935d3446824308-7c6a0cc2b49be90b40f89947237cdc02-462-com.django.acme.service.message.RefreshMessage-true-false
               "server_message_id": "2413932699242790854",
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4090-com.django.acme.service.message.RefreshMessage-true-false
w570160d72d5f7e6883ca1a65-bf678651f538b058ca59b0fa2d6b4cf1-6180-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:28:27,354] 1777619627 INFO  [client-handler-worker-29] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match for auth:  URI: /acme/sync/v1/0d9b35a8e9ad052409fe27a05bd120e1 AuthTokens: djangoAccount = 275757838, djangoDevice = b41114c0e4640a746ff3cbf2d8994de9,
v5709aee7689d1f1628cff0a7-5cd32f344b73eecc77e36b75f825ea4a-685-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:29:28,949] 1777681222 INFO  [client-handler-worker-1] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digest calculation message: POST/discovery/v3/swipelist.protodjango-auth-token<DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>J3qTOz2nm9r0jxrZqHIrUQ</Principal><Token>QSE9W0vz1OGBEHHxDB3GO06Bz6KCfzfdmBTG9tkHjBLeOF2RD3HHoHO9uc8FDfPy</Token><Signature>ENFq3uj5j6V7sgom6b5nxDOsb8c2+owriCixK6iXpFc=</Signature><AppId>5KD-PXR_bovYufXc6Es0QQ</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>7i99v26sK6PNym-qEtMsfT8fZ8gK_Z3a9wIzIFJWF_XeOF2RD3HHoHO9uc8FDfPy</Principal><Token>QSE9W0vz1OGBEHHxDB3GO06Bz6KCfzfdmBTG9tkHjBLeOF2RD3HHoHO9uc8FDfPy</Token><Signature>UdO8+5WoSepkBig98U1iNYSCVwRjR1EGjTrQDujMXug=</Signature><AppId>5KD-PXR_bovYufXc6Es0QQ</AppId></DjangoAuthToken></DjangoAuthTokens>django-body-compressedresdjango-body-encryptedbothdjango-cipher-nameDJANGO1111django-cipher-version1.0v6JhUw6VNuKDvuR+bINCKDB3Zdjpk3dfl6bAM2rFNTg=
v570aaa6649021789b915d8c3-9a9d4fad3cde34d34889d1ab0b8c2fd6-146-com.django.acme.service.message.RefreshMessage-true-false
w570b8782f1b66fcd8a3ffd0b-232fc99806f0654f6b02df8c32d6a9c4-2502-com.django.acme.service.message.RefreshMessage-true-false
w5705232b73868d7c515e09c6-04b313e55ec883f6a9b8edf5b4636ecb-3434-com.django.acme.service.message.RefreshMessage-true-false
u570d25a801f66b998e1b8014-d7cc61256e2078bf5f4468e63a464037-76-com.django.acme.service.message.RefreshMessage-true-false
   "last_read_update_request": {
v570d81740e7747c859332799-cf7124f5031070215a060a94f4313805-483-com.django.acme.service.message.RefreshMessage-true-false
v5706d74be16664acbf6139b2-18e29bc909ce30b5025ed579a4b968be-944-com.django.acme.service.message.RefreshMessage-true-false
v570a739dc073c746332d8c6b-1778e600e254e0779b43cb92af2b9ef9-403-com.django.acme.service.message.RefreshMessage-true-false
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4192-com.django.acme.service.message.RefreshMessage-true-false
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4148-com.django.acme.service.message.RefreshMessage-true-false
u56face9dc210d66636e393d7-5cfca35b9325f27ae58dbae103f19077-62-com.django.acme.service.message.RefreshMessage-true-false
w5700ec11e16664acbf62a86a-2523fa929cdcf28b7ebd3e676a874ea6-1741-com.django.acme.service.message.RefreshMessage-true-false
w5700ec11e16664acbf62a86a-2523fa929cdcf28b7ebd3e676a874ea6-1692-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:36:43,475] 1778115748 WARN  [proxy-handler-worker-5] com.django.taas.auth.handler.RecipientHandler - in messageRecieved inboundChannel was closed ignoring setting of channel ops.[id: 0x2627cd97, /10.102.11.54:21569 => us0101ame-vip001/10.101.10.80:8080] RECEIVED: DefaultHttpResponse(chunked: false) HTTP/1.1 200 OK Content-Type: application/x-protobuf;charset=ISO-8859-1 Content-Language: en-US Content-Length: 183 Date: Wed, 13 Apr 2016 17:36:42 GMT Server: us0101ame001, Connection Id = [id: 0x81c252ed, /188.212.225.53:39353 => /199.83.169.114:8080] RECEIVED: DefaultHttpRequest(chunked: false) POST /acme/sync/v1/e97c95292763d613ef20ea57314d847a HTTP/1.1 Host: 199.83.169.50 Accept: */* Accept-Encoding: deflate, gzip DjangoMe-TaskId: 92 Django-Cipher-Name: DJANGO1111 Django-Cipher-Version: 1.0 Django-Auth-Token: <DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>gl8gkbTurqOFD_rg7VX9KQ</Principal><Token>5AGMTRpNVOwUz6XmhekmLhLxcRX_k4cA8ycJPZKNtRfeOF2RD3HHoHO9uc8FDfPy</Token><Signature>+eeYmeLf8D4PO3+JXcokD0NfNlSPILHg057I9UpM8Hs=</Signature></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>ZxsY4rNQ0K_zIhiIRMNGckaAyMuBlqXkbPTg_-AdgA_eOF2RD3HHoHO9uc8FDfPy</Principal><Token>5AGMTRpNVOwUz6XmhekmLhLxcRX_k4cA8ycJPZKNtRfeOF2RD3HHoHO9uc8FDfPy</Token><Signature>vam1KGd1d3qvibIAtWmuAeQl28DtPAylhvpxbuA40tY=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken></DjangoAuthTokens> Django-Body-Encrypted: none Django-Body-Compressed: none Django-Digest: Yi1te4YaO7ncn3bBO7sgmwfdvbE= Content-Type: application/x-protobuf X-Forwarded-For: 188.212.225.53 Content-Length: 120 X-DjangoAuth-Username: e97c95292763d613ef20ea57314d847a X-DjangoAuth-AppId: django X-DjangoAuth-AccountId: 1140200900
[2016-04-13T17:37:22,590] 1778154863 INFO  [client-handler-worker-35] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Authentication failed  URI: /profilerator/v1/profiles.proto AuthTokens: djangoAccount = 370739903, djangoAccount [appid] = djangosocial, djangoDevice = 4fb486d2bddf41c151c29cc6e81ab83d, djangoDevice [appid] = djangosocial,
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_25]
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-410-com.django.acme.service.message.RefreshMessage-true-false
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-384-com.django.acme.service.message.RefreshMessage-true-false
       "direction": "1",
[2016-04-13T17:48:52,117] 1778844390 WARN  [proxy-handler-worker-40] com.django.taas.auth.handler.RecipientHandler - in messageRecieved inboundChannel was closed ignoring setting of channel ops.[id: 0xf3418a84, /10.102.11.54:46805 => us0101afe-vip001/10.100.51.15:8080] RECEIVED: DefaultHttpResponse(chunked: false) HTTP/1.1 200 OK Content-Type: application/json Date: Wed, 13 Apr 2016 17:48:51 GMT Server: us0101afe002 Content-Length: 856, Connection Id = [id: 0x133ba587, /176.16.0.17:54571 => /199.83.169.114:8080] RECEIVED: DefaultHttpRequest(chunked: false) POST /feed/v6/like/302012827088981217 HTTP/1.1 Host: like.django.me Accept-Encoding: deflate, gzip Accept: application/json DjangoMe-TaskId: 2248 Django-Cipher-Name: DJANGO1111 Django-Cipher-Version: 1.0 Django-Auth-Token: <DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>E-vAvp5Y7vM5onIUgwek9A</Principal><Token>DBTZtt1bBDr8s1FpS7kf0dKHUCL2b0JSOQNSoQ994k7eOF2RD3HHoHO9uc8FDfPy</Token><Signature>HQvHsIy6wXCeS7gI55Cx+oD+N/gR8DpldK2/pQ/e7n8=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>Tmxcbqi7-DF5C4xfH8jLPMLnOaphbCup4rGUdkTa3tveOF2RD3HHoHO9uc8FDfPy</Principal><Token>DBTZtt1bBDr8s1FpS7kf0dKHUCL2b0JSOQNSoQ994k7eOF2RD3HHoHO9uc8FDfPy</Token><Signature>1Sxin1WdkVmD/zoSOW3YMIXiY4nXlKJdbZp5y/l6/10=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken></DjangoAuthTokens> Django-Body-Encrypted: both Django-Body-Compressed: none Django-Digest: 4psW5qCx4zi824KSGVobCnFjpq0= Content-Type: application/json X-Forwarded-For: 176.16.0.17 Content-Length: 25 X-DjangoAuth-Username: b24c42d43f6feecab34821b6e99edf18 X-DjangoAuth-AccountId: 429359899 X-DjangoAuth-AppId: django
v570a4d631b62caf5311f5dab-0b9cff8803de9c719e215c6cedb878bb-244-com.django.acme.service.message.RefreshMessage-true-false
w56f958cb1ce926ee9d7a45e0-c7facde81e5a32522c4c5ca20f438e6e-3833-com.django.acme.service.message.RefreshMessage-true-false
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-345-com.django.acme.service.message.RefreshMessage-true-false
v5707c031d0c1126c6ea9c43d-87554f5dd3ec93f0f5a0fcb0e1414af5-227-com.django.acme.service.message.RefreshMessage-true-false
w5703fa12d0c1126c6e0c6777-86c63a77b4be7f750aa092cd91478519-1346-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:49:29,651] 1778881924 INFO  [client-handler-worker-35] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digest calculation message: POST/acme/sync/v1/6565808015f66369c0a0840e08d6c524django-auth-token<DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>uHUaPOjkoykCy-G6siDIkg</Principal><Token>_gUxpfQh_69X7GosybBPe9ZcNkJWVgyMVX5dEyUNgBTeOF2RD3HHoHO9uc8FDfPy</Token><Signature>Y/8GFdjTHqP9l1iEChkBq7ThBgII96MtTseJdzAyrB0=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>j29dkXrHEFBB9s490R0GtksVSBAMYrCzaBEYMi0VgMDeOF2RD3HHoHO9uc8FDfPy</Principal><Token>_gUxpfQh_69X7GosybBPe9ZcNkJWVgyMVX5dEyUNgBTeOF2RD3HHoHO9uc8FDfPy</Token><Signature>FNSBqqqi+PJ2LNcrKICf+r691WT1xyrv5IJWJ4MQtqQ=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken></DjangoAuthTokens>django-body-compressednonedjango-body-encryptednonedjango-cipher-nameDJANGO1111django-cipher-version1.0�R
[2016-04-13T17:49:39,187] 1778891460 INFO  [client-handler-worker-45] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match for auth:  URI: /profilerator/v1/profiles.proto AuthTokens: djangoAccount = 2386282937, djangoAccount [appid] = Django, djangoDevice = 05396762ff718e4ec7d25a15bcbee546, djangoDevice [appid] = Django,
v570d04a43da1ee514b1710c7-6c3dc89cfbb014e6ca6835aa7583732e-110-com.django.acme.service.message.RefreshMessage-true-false
 at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.6.6.Final.jar:?]
v570acb36fc0fe40ba24029fd-038448a16fb19275d5ebcdd99aa6b211-457-com.django.acme.service.message.RefreshMessage-true-false
v570266f6e16664acbfa0f61d-1b8e8d697e9aea357f82eecad32c215a-363-com.django.acme.service.message.RefreshMessage-true-false
org.jboss.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 26214400 bytes.
w56fe27c7c0c5c785e78b78c8-7a2b594f18ceaf769b00af17d473f982-2968-com.django.acme.service.message.RefreshMessage-true-false
v570acb36fc0fe40ba24029fd-038448a16fb19275d5ebcdd99aa6b211-331-com.django.acme.service.message.RefreshMessage-true-false
w57056fc485e8f79c93b70afb-6bd87092b50e518e41a864fbc9dfc284-3075-com.django.acme.service.message.RefreshMessage-true-false
v570b98a8967f00800f68aedb-735e1879ffc8c7bce02af3283d4c5f30-813-com.django.acme.service.message.RefreshMessage-true-false
w56f95be22d5f7e6883760ba9-c6677f263d4566a08d41dee3848486d7-9287-com.django.acme.service.message.RefreshMessage-true-false

w570160d72d5f7e6883ca1a65-bf678651f538b058ca59b0fa2d6b4cf1-5919-com.django.acme.service.message.RefreshMessage-true-false
v570395b4696b8b2ae9af6f7a-cfedda87b25e3c695941e552507f9d93-941-com.django.acme.service.message.RefreshMessage-true-false
v56ffe71549021789b947afa8-14ba0e542284eff4d16b41bafa2bfada-635-com.django.acme.service.message.RefreshMessage-true-false
Apr 13 11:25:47 us0101bac024 access.log  27.70.138.58 - - [13/Apr/2016:18:25:45 +0000] "POST /acme/sync/v1/13f9d790b2dc56d218f64e9b59b1cc29 HTTP/1.1" 200 170 B "proxy-handler-worker-18" 5 ms us0101bac024.djangome.gbl 1694682706 13f9d790b2dc56d218f64e9b59b1cc29 django
x56f4a484ce8b6e2cccde1a6b-f599b3b4cc7d61f051a23ee58c51c3ba-14447-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T18:10:00,697] 1780112970 INFO  [client-handler-worker-19] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Authentication failed  URI: /acme/sync/v1/b8d6e5dad4bea5b7cba85ffd0c410ab4 AuthTokens: djangoAccount = 2397026295, djangoAccount [appid] = django, djangoDevice = 7bc5f9890089a80ab6b422a1ef4de0d2, djangoDevice [appid] = django,
w570c6206c4afd121cfebf351-f87d6cbf5f8e4425536aeaab9ee7d8e6-1016-com.django.acme.service.message.RefreshMessage-true-false
w5701169e89e88eada96fecc8-ab9a3ea70933a6d092159cdbadf78036-4920-com.django.acme.service.message.RefreshMessage-true-false
w570818e4c4afd121cf37bba9-50d9d98d2d9e57ffde1ac1ddf2522238-1094-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T18:09:45,779] 1780098052 INFO  [client-handler-worker-2] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match for auth:  URI: /acme/sync/v1/22c92918d1916dbe2fa06ef61e61b299 AuthTokens: djangoAccount = 769869396, djangoAccount [appid] = djangosocial, djangoDevice = dc2f2c9a40f01b882689305e3019c6e5, djangoDevice [appid] = djangosocial,
w56fefcf801f66b998eb247df-d77fb1371c53657833f874ff560108f6-2363-com.django.acme.service.message.RefreshMessage-true-false
v570c685d73935d3446824308-7c6a0cc2b49be90b40f89947237cdc02-463-com.django.acme.service.message.RefreshMessage-true-false
               "server_ts": "1460331644503"
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4121-com.django.acme.service.message.RefreshMessage-true-false
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4091-com.django.acme.service.message.RefreshMessage-true-false
w570160d72d5f7e6883ca1a65-bf678651f538b058ca59b0fa2d6b4cf1-6181-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:28:27,354] 1777619627 INFO  [client-handler-worker-29] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Authentication failed  URI: /acme/sync/v1/0d9b35a8e9ad052409fe27a05bd120e1 AuthTokens: djangoAccount = 275757838, djangoDevice = b41114c0e4640a746ff3cbf2d8994de9,
v5709aee7689d1f1628cff0a7-5cd32f344b73eecc77e36b75f825ea4a-686-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:29:28,949] 1777681222 INFO  [client-handler-worker-1] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match for auth:  URI: /discovery/v3/swipelist.proto AuthTokens: djangoAccount = 382744381, djangoAccount [appid] = djangosocial, djangoDevice = 29b6b5996e580d2e4f63e7038c645ab7, djangoDevice [appid] = djangosocial,
v570d31d1ea7e840697fe7aed-15b45f3a71a6643693043a72dfed795a-157-com.django.acme.service.message.RefreshMessage-true-false
w570160d72d5f7e6883ca1a65-bf678651f538b058ca59b0fa2d6b4cf1-5678-com.django.acme.service.message.RefreshMessage-true-false
v570d31d1ea7e840697fe7aed-15b45f3a71a6643693043a72dfed795a-134-com.django.acme.service.message.RefreshMessage-true-false
v570aaa6649021789b915d8c3-9a9d4fad3cde34d34889d1ab0b8c2fd6-147-com.django.acme.service.message.RefreshMessage-true-false
w570b8782f1b66fcd8a3ffd0b-232fc99806f0654f6b02df8c32d6a9c4-2503-com.django.acme.service.message.RefreshMessage-true-false
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4288-com.django.acme.service.message.RefreshMessage-true-false
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4254-com.django.acme.service.message.RefreshMessage-true-false
w5701622d2d5f7e6883ca659e-bf678651f538b058ca59b0fa2d6b4cf1-3127-com.django.acme.service.message.RefreshMessage-true-false
u570d25a801f66b998e1b8014-d7cc61256e2078bf5f4468e63a464037-77-com.django.acme.service.message.RefreshMessage-true-false
       "set_badge_by_context": [
}
w570160d72d5f7e6883ca1a65-bf678651f538b058ca59b0fa2d6b4cf1-5850-com.django.acme.service.message.RefreshMessage-true-false
v570a739dc073c746332d8c6b-1778e600e254e0779b43cb92af2b9ef9-404-com.django.acme.service.message.RefreshMessage-true-false
u570ad22a32df0544166ff41e-1821c1b80e3310e07f0e90bffb666a6f-99-com.django.acme.service.message.RefreshMessage-true-false
v56fa8a13c210d66636d520c0-5cfca35b9325f27ae58dbae103f19077-264-com.django.acme.service.message.RefreshMessage-true-false
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_25]
w570486d76eeba622450cb81b-30a348d3b29763ff1765ffd035684ca6-2184-com.django.acme.service.message.RefreshMessage-true-false
v570a739dc073c746332d8c6b-1778e600e254e0779b43cb92af2b9ef9-370-com.django.acme.service.message.RefreshMessage-true-false
w5700ec11e16664acbf62a86a-2523fa929cdcf28b7ebd3e676a874ea6-1742-com.django.acme.service.message.RefreshMessage-true-false
w570486d76eeba622450cb81b-30a348d3b29763ff1765ffd035684ca6-2201-com.django.acme.service.message.RefreshMessage-true-false
w5704c83aea7e840697924197-57d12ebd855de534ef5431fe2c75fef2-7221-com.django.acme.service.message.RefreshMessage-true-false
v570b94795572cb57a295a78d-8c51590831f74aacbc4631d9dd25b583-468-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:37:22,620] 1778154893 INFO  [client-handler-worker-20] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match: statedDigest=h2pgkQfx8a0DS4S0bvqQnPqVfCI=, calcDigest=H7qd/hoYeMi1LvolCRPhNg6XHg8=
 at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.6.6.Final.jar:?]
v5702291716c80bc7fc2f7679-59d12ec5234694940a248fa63f7ae9de-743-com.django.acme.service.message.RefreshMessage-true-false
v570c6206c4afd121cfebf351-f87d6cbf5f8e4425536aeaab9ee7d8e6-970-com.django.acme.service.message.RefreshMessage-true-false
 at com.django.taas.auth.handler.ReadingEventGenerateHandler.messageReceived(ReadingEventGenerateHandler.java:20) ~[authConsumer.jar:?]
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-441-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:44:57,954] 1778610227 ERROR [proxy-handler-worker-9] com.django.taas.auth.handler.RecipientHandler - Exception happened while processing request to protected server [id: 0x26a16a39, /10.102.11.54:33746 => us0101gc-vip001/10.100.11.121:8080] EXCEPTION: org.jboss.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 26214400 bytes., Connection Id = [id: 0x2981cb6a, /87.109.133.107:55724 => /199.83.169.114:8080] RECEIVED: DefaultHttpRequest(chunked: false) POST /tc2/v1/message/get HTTP/1.1 Host: tc2.django.me Accept-Encoding: deflate, gzip Accept: application/json DjangoMe-TaskId: 1109 Django-Cipher-Name: DJANGO1111 Django-Cipher-Version: 1.0 Django-Auth-Token: <DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>Y9NbUKDeqlpiRpNTRMgN0-v7X03lYXzjrUO212JlLWc</Principal><Token>RlL6EqhUlh2v1M130vgNaIjGfgBnd60fZuCS0z60Yl7eOF2RD3HHoHO9uc8FDfPy</Token><Signature>tIRoekyxdXu94eFksqh+nmC+Jdt8HHqPDI1edSCqWXE=</Signature><AppId>5KD-PXR_bovYufXc6Es0QQ</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>IviY7B1aJizVHC10f6-7leSbr65tRXVtfRuMXBLXYEreOF2RD3HHoHO9uc8FDfPy</Principal><Token>RlL6EqhUlh2v1M130vgNaIjGfgBnd60fZuCS0z60Yl7eOF2RD3HHoHO9uc8FDfPy</Token><Signature>b+v1wo9HxN8TtyR+0x4lbwwyf4VhabkJS6hzPnESN0Y=</Signature><AppId>5KD-PXR_bovYufXc6Es0QQ</AppId></DjangoAuthToken></DjangoAuthTokens> Django-Body-Encrypted: none Django-Body-Compressed: none Django-Digest: 5NsirTN8ntr7MqJhAYvOroyY4jM= Content-Type: application/json; charset=utf-8 X-Forwarded-For: 87.109.133.107 Content-Length: 311 X-DjangoAuth-Username: 3930d3578dc573f98adcf9928a1afc49 X-DjangoAuth-AccountId: 53229003;149522353 X-DjangoAuth-AppId: djangosocial
[2016-04-13T17:48:19,818] 1778812091 INFO  [client-handler-worker-13] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digest calculation message: POST/tc2/v1/rr/getdjango-auth-token<DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>RbJzeWTPyQgiIZJfzp10xQ</Principal><Token>32GtUXS8fAceCpQGe0fxSG8AlHYqymFpOV0VSrQvrLneOF2RD3HHoHO9uc8FDfPy</Token><Signature>J41CZU+Fu2eQ0VzIwNQkfZdwa6+k4Sym+vZ7CUUa144=</Signature><AppId>5KD-PXR_bovYufXc6Es0QQ</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>wb5smtoCcK_yhSdSnGQmMNss8EvKNMd5PDfCJkTKa8feOF2RD3HHoHO9uc8FDfPy</Principal><Token>32GtUXS8fAceCpQGe0fxSG8AlHYqymFpOV0VSrQvrLneOF2RD3HHoHO9uc8FDfPy</Token><Signature>sW1tDBjzRhjTIIdO0MWR8tngTrfWW446WdILGDn71GM=</Signature><AppId>5KD-PXR_bovYufXc6Es0QQ</AppId></DjangoAuthToken></DjangoAuthTokens>django-body-compressednonedjango-body-encryptednonedjango-cipher-nameDJANGO1111django-cipher-version1.0{
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_25]
w570160d72d5f7e6883ca1a65-bf678651f538b058ca59b0fa2d6b4cf1-5920-com.django.acme.service.message.RefreshMessage-true-false
v570395b4696b8b2ae9af6f7a-cfedda87b25e3c695941e552507f9d93-942-com.django.acme.service.message.RefreshMessage-true-false
w570c6206c4afd121cfebf351-f87d6cbf5f8e4425536aeaab9ee7d8e6-1017-com.django.acme.service.message.RefreshMessage-true-false
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4289-com.django.acme.service.message.RefreshMessage-true-false
           {

w570486d76eeba622450cb81b-30a348d3b29763ff1765ffd035684ca6-2186-com.django.acme.service.message.RefreshMessage-true-false
w570486d76eeba622450cb81b-30a348d3b29763ff1765ffd035684ca6-2203-com.django.acme.service.message.RefreshMessage-true-false
v5709a904c4fd1049eec724b0-4727ced9772724aa3da7325db8588f8c-563-com.django.acme.service.message.RefreshMessage-true-false
v570c6206c4afd121cfebf351-f87d6cbf5f8e4425536aeaab9ee7d8e6-971-com.django.acme.service.message.RefreshMessage-true-false
w56fff4b02ab586117f929e73-4e9f8a5c1d176425f72457be00d23cd1-7406-com.django.acme.service.message.RefreshMessage-true-false
w56f958cb1ce926ee9d7a45e0-c7facde81e5a32522c4c5ca20f438e6e-3835-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:49:39,233] 1778891506 WARN  [proxy-handler-worker-28] com.django.taas.auth.handler.RecipientHandler - in messageRecieved inboundChannel was closed ignoring setting of channel ops.[id: 0x52c7ff63, /10.102.11.54:18409 => us0101ads-vip001/10.100.51.17:8080] RECEIVED: DefaultHttpResponse(chunked: false) HTTP/1.1 200 OK Pragma: no-cache Cache-Control: no-cache, no-store, max-age=0 Expires: Thu, 01 Jan 1970 00:00:00 GMT Content-Type: application/json;charset=UTF-8 Content-Language: en-US Date: Wed, 13 Apr 2016 17:49:38 GMT Server: us0101ads004 Content-Length: 117, Connection Id = [id: 0x998be834, /156.203.209.73:46416 => /199.83.169.114:8080] RECEIVED: DefaultHttpRequest(chunked: false) POST /sdkStorage/v1/c59a0bd505c1ac6d20e8825dd58c3c0120472f26/QW5kcm9pZF9ENTMyMl9ENTMyMg%3D%3D/2.14.2.191673/possession.json HTTP/1.1 Host: ipa.django.me Accept: */* Accept-Encoding: deflate, gzip DjangoMe-TaskId: 129 Django-Cipher-Name: DJANGO1111 Django-Cipher-Version: 1.0 Django-Auth-Token: <DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoSdk</Type><Cipher>DJANGO3333</Cipher><Version>1.0</Version><Principal>Y0yO8Dy7mm5r9o2RMnJXWBYByTSZBRIBLatnT_j4jBhC_OSLc886VhlfCMmMIDiOYD6eM-f-Y_iKclO4DgRWyZXzz-MPJp9GrFRKBEeORbU</Principal><Token>lrDGb79RI_hNfVKsFkoHH8Gr6zBgqU4EyLDAtrLbmLn6C5hYoXhzjbcvW8n6fvQw</Token><Expiration>1775205070</Expiration><Signature>s4fWObVHJsMo+0uUfTAOnpTqvym1Bcya/3RC5v8Yjkc=</Signature></DjangoAuthToken></DjangoAuthTokens> Django-Body-Encrypted: both Django-Body-Compressed: res Django-Digest: 3SxlPR+C/4OTQaHpO0o1dJro3jc= Content-Type: application/json X-Forwarded-For: 156.203.209.73 Content-Length: 849 X-DjangoAuth-Sdk-Urn: urn:django:token:1.0:Django:RoadRiot:2413605831{"access":[1,2,3,4],"grp":[]}
w56fe27c7c0c5c785e78b78c8-7a2b594f18ceaf769b00af17d473f982-2970-com.django.acme.service.message.RefreshMessage-true-false
u570d0a539cbc071798d9b4c0-1dff5657e00cbb55e9a55e6d221ab520-92-com.django.acme.service.message.RefreshMessage-true-false
x56f4a484ce8b6e2cccde1a6b-f599b3b4cc7d61f051a23ee58c51c3ba-14449-com.django.acme.service.message.RefreshMessage-true-false
v570d31d1ea7e840697fe7aed-15b45f3a71a6643693043a72dfed795a-159-com.django.acme.service.message.RefreshMessage-true-false
v570a739dc073c746332d8c6b-1778e600e254e0779b43cb92af2b9ef9-406-com.django.acme.service.message.RefreshMessage-true-false
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
w570486d76eeba622450cb81b-30a348d3b29763ff1765ffd035684ca6-2187-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:37:22,620] 1778154893 INFO  [client-handler-worker-20] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match for auth:  URI: /sdkProfilerator/v1/ce536e6072f958eb1292667405e666498653a702/QW5kcm9pZF9TTS1HOTAwSF9rM2d4eA%3D%3D/2.14.2.191673/search/single AuthTokens: djangoSdk = urn:django:token:1.0:Django:RoadRiot:1097571726{"access":[1,2,3,4],"grp":[]},
v5709a904c4fd1049eec724b0-4727ced9772724aa3da7325db8588f8c-564-com.django.acme.service.message.RefreshMessage-true-false
v570c6206c4afd121cfebf351-f87d6cbf5f8e4425536aeaab9ee7d8e6-972-com.django.acme.service.message.RefreshMessage-true-false
w56f958cb1ce926ee9d7a45e0-c7facde81e5a32522c4c5ca20f438e6e-3836-com.django.acme.service.message.RefreshMessage-true-false
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-348-com.django.acme.service.message.RefreshMessage-true-false
v570d04a43da1ee514b1710c7-6c3dc89cfbb014e6ca6835aa7583732e-113-com.django.acme.service.message.RefreshMessage-true-false
u570d0a539cbc071798d9b4c0-1dff5657e00cbb55e9a55e6d221ab520-93-com.django.acme.service.message.RefreshMessage-true-false
w570160d72d5f7e6883ca1a65-bf678651f538b058ca59b0fa2d6b4cf1-5922-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T18:10:01,826] 1780114099 WARN  [proxy-handler-worker-4] com.django.taas.auth.handler.RecipientHandler - in messageRecieved inboundChannel was closed ignoring setting of channel ops.[id: 0xe9b2b011, /10.102.11.54:56210 => us0101afe-vip001/10.100.51.15:8080] RECEIVED: DefaultHttpResponse(chunked: false) HTTP/1.1 200 OK Content-Type: application/json Date: Wed, 13 Apr 2016 18:10:01 GMT Server: us0101afe004 Content-Length: 14854, Connection Id = [id: 0x7d54e405, /37.202.76.181:33628 => /199.83.169.114:8080] RECEIVED: DefaultHttpRequest(chunked: false) POST /feed/v5/feed/count_batch HTTP/1.1 Host: like.django.me Accept-Encoding: deflate, gzip Accept: application/json DjangoMe-TaskId: 176 Django-Cipher-Name: DJANGO1111 Django-Cipher-Version: 1.0 Django-Auth-Token: <DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>6RYvax1LZFVBLOgRhnnnRA</Principal><Token>Z7l2Ox2Ypr3WrAhtX49xJCXyTrfXI14uaFUfMuT_ch_eOF2RD3HHoHO9uc8FDfPy</Token><Signature>4jM4eeZHwb/lmg6Xqnm/B0KMOW4XMjd8zlCcIbhKliI=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>rI3QOvVOXvSlvAcNrozcUJ7MyIfNOUVpjoQPB6C_HibeOF2RD3HHoHO9uc8FDfPy</Principal><Token>Z7l2Ox2Ypr3WrAhtX49xJCXyTrfXI14uaFUfMuT_ch_eOF2RD3HHoHO9uc8FDfPy</Token><Signature>gq3b7GWKKxS5VkucPji7B1WZbzUD3W/IDhCIVptssow=</Signature><AppId>BWo0CgCPRn73wODGqqIIKg</AppId></DjangoAuthToken></DjangoAuthTokens> Django-Body-Encrypted: both Django-Body-Compressed: none Django-Digest: +PLwJylJ39rerSlhjlmQ93to2kk= Content-Type: application/json X-Forwarded-For: 37.202.76.181 Content-Length: 395 X-DjangoAuth-Username: 011549b9b8f6c208ecb5924a9d4c4e3b X-DjangoAuth-AccountId: 447309771 X-DjangoAuth-AppId: django
v570aaa6649021789b915d8c3-9a9d4fad3cde34d34889d1ab0b8c2fd6-150-com.django.acme.service.message.RefreshMessage-true-false
w5705232b73868d7c515e09c6-04b313e55ec883f6a9b8edf5b4636ecb-3438-com.django.acme.service.message.RefreshMessage-true-false
v570a7941c073c746332eac05-1778e600e254e0779b43cb92af2b9ef9-291-com.django.acme.service.message.RefreshMessage-true-false
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4196-com.django.acme.service.message.RefreshMessage-true-false
w5700ec11e16664acbf62a86a-2523fa929cdcf28b7ebd3e676a874ea6-1696-com.django.acme.service.message.RefreshMessage-true-false
v570e4b7c32df054416ff1d67-2b54ed0d78fdaaf92c3298664c78cc42-218-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:36:57,309] 1778129582 INFO  [client-handler-worker-31] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match for auth:  URI: /profilerator/v1/profiles.proto AuthTokens: djangoAccount = 370739903, djangoAccount [appid] = djangosocial, djangoDevice = 4fb486d2bddf41c151c29cc6e81ab83d, djangoDevice [appid] = djangosocial,
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-414-com.django.acme.service.message.RefreshMessage-true-false
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-388-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:48:52,890] 1778845163 INFO  [client-handler-worker-5] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digests dont match: statedDigest=LYNgCUCYI/PKdF/Gh585V5X2deA=, calcDigest=vptALhfFoJt2TZzluKnwE/1TbqU=
w5703fa12d0c1126c6e0c6777-86c63a77b4be7f750aa092cd91478519-1350-com.django.acme.service.message.RefreshMessage-true-false
v570266f6e16664acbfa0f61d-1b8e8d697e9aea357f82eecad32c215a-368-com.django.acme.service.message.RefreshMessage-true-false
v570b98a8967f00800f68aedb-735e1879ffc8c7bce02af3283d4c5f30-817-com.django.acme.service.message.RefreshMessage-true-false
v56ffe71549021789b947afa8-14ba0e542284eff4d16b41bafa2bfada-639-com.django.acme.service.message.RefreshMessage-true-false
               "server_ts": "1460358353617"
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4292-com.django.acme.service.message.RefreshMessage-true-false
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4258-com.django.acme.service.message.RefreshMessage-true-false
v570ad23832df0544166ff6de-1821c1b80e3310e07f0e90bffb666a6f-103-com.django.acme.service.message.RefreshMessage-true-false
v570a739dc073c746332d8c6b-1778e600e254e0779b43cb92af2b9ef9-374-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:37:22,924] 1778155197 ERROR [client-handler-worker-20] com.django.taas.auth.handler.HttpChannelStateHandler - Exception while processing request [id: 0x3685954b, /212.34.11.5:50028 => /199.83.169.114:8080] EXCEPTION: java.lang.IllegalArgumentException: invalid version format: XMLNS="COM:DJANGO:UTIL:CRYPTO:AUTH:JAXB" XMLNS:NS2="COM:DJANGO:UTIL:CRYPTO:JAXB:V1:AUTHRSP" XMLNS:NS3="SERVICE:DJANGO:TS:1"><DJANGOAUTHTOKEN><TYPE>DJANGOACCOUNT</TYPE><CIPHER>DJANGO1111</CIPHER><VERSION>1.0</VERSION><PRINCIPAL>GUG-YG40YHTAPRJHHF4PGW</PRINCIPAL><TOKEN>LIRRX7D-FLGFDZNU3J0OQKCLILQB5XIOS3XL_X1EA5BEOF2RD3HHOHO9UC8FDFPY</TOKEN><SIGNATURE>B2HIYVAGSVCZYYBWXUYHSB0I9CBXWFCU+RRM5WNSI3G=</SIGNATURE></DJANGOAUTHTOKEN><DJANGOAUTHTOKEN><TYPE>DJANGODEVICE</TYPE><CIPHER>DJANGO1111</CIPHER><VERSION>1.0</VERSION><PRINCIPAL>YMRJGEQZCIGVSPJGD8MJYDH2QR9-ITGJ7RJW9-7RH8JEOF2RD3HHOHO9UC8FDFPY</PRINCIPAL><TOKEN>LIRRX7D-FLGFDZNU3J0OQKCLILQB5XIOS3XL_X1EA5BEOF2RD3HHOHO9UC8FDFPY</TOKEN><SIGNATURE>HTPIRIXVSEXZO7GUFY6AF0+7EX7W9PPE/BTJDZ8QMIC=</SIGNATURE></DJANGOAUTHTOKEN></DJANGOAUTHTOKENS>
 at com.django.taas.auth.handler.AccessLogHandler.messageReceived(AccessLogHandler.java:110) ~[authConsumer.jar:?]
w56fff4b02ab586117f929e73-4e9f8a5c1d176425f72457be00d23cd1-7409-com.django.acme.service.message.RefreshMessage-true-false
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-350-com.django.acme.service.message.RefreshMessage-true-false
v570d04a43da1ee514b1710c7-6c3dc89cfbb014e6ca6835aa7583732e-115-com.django.acme.service.message.RefreshMessage-true-false
u570d0a539cbc071798d9b4c0-1dff5657e00cbb55e9a55e6d221ab520-95-com.django.acme.service.message.RefreshMessage-true-false
x56f4a484ce8b6e2cccde1a6b-f599b3b4cc7d61f051a23ee58c51c3ba-14452-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T18:09:46,067] 1780098340 INFO  [client-handler-worker-9] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Authentication failed  URI: /profilerator/v1/profiles.proto AuthTokens: djangoAccount = 40231598, djangoAccount [appid] = djangosocial, djangoDevice = 7a6d6a17d27aad47f212f57cf42b6303, djangoDevice [appid] = djangosocial,
v570b879bd4bd0a78344daa44-506480288c56185be03a7137acf16d00-906-com.django.acme.service.message.RefreshMessage-true-false
v5706d74be16664acbf6139b2-18e29bc909ce30b5025ed579a4b968be-950-com.django.acme.service.message.RefreshMessage-true-false
   "last_read_update_request": {
w5700e984e16664acbf624768-2523fa929cdcf28b7ebd3e676a874ea6-4154-com.django.acme.service.message.RefreshMessage-true-false
u56face9dc210d66636e393d7-5cfca35b9325f27ae58dbae103f19077-68-com.django.acme.service.message.RefreshMessage-true-false
w5700ec11e16664acbf62a86a-2523fa929cdcf28b7ebd3e676a874ea6-1747-com.django.acme.service.message.RefreshMessage-true-false
w570486d76eeba622450cb81b-30a348d3b29763ff1765ffd035684ca6-2208-com.django.acme.service.message.RefreshMessage-true-false
w5704c83aea7e840697924197-57d12ebd855de534ef5431fe2c75fef2-7226-com.django.acme.service.message.RefreshMessage-true-false
v570b94795572cb57a295a78d-8c51590831f74aacbc4631d9dd25b583-473-com.django.acme.service.message.RefreshMessage-true-false
w5700ec11e16664acbf62a86a-2523fa929cdcf28b7ebd3e676a874ea6-1698-com.django.acme.service.message.RefreshMessage-true-false
w56fd2c5a83df18631408cb09-728de128e1665430314c7f706353e97d-3285-com.django.acme.service.message.RefreshMessage-true-false
java.lang.IllegalArgumentException: invalid version format: XMLNS="COM:DJANGO:UTIL:CRYPTO:AUTH:JAXB" XMLNS:NS2="COM:DJANGO:UTIL:CRYPTO:JAXB:V1:AUTHRSP" XMLNS:NS3="SERVICE:DJANGO:TS:1"><DJANGOAUTHTOKEN><TYPE>DJANGOACCOUNT</TYPE><CIPHER>DJANGO1111</CIPHER><VERSION>1.0</VERSION><PRINCIPAL>GUG-YG40YHTAPRJHHF4PGW</PRINCIPAL><TOKEN>LIRRX7D-FLGFDZNU3J0OQKCLILQB5XIOS3XL_X1EA5BEOF2RD3HHOHO9UC8FDFPY</TOKEN><SIGNATURE>B2HIYVAGSVCZYYBWXUYHSB0I9CBXWFCU+RRM5WNSI3G=</SIGNATURE></DJANGOAUTHTOKEN><DJANGOAUTHTOKEN><TYPE>DJANGODEVICE</TYPE><CIPHER>DJANGO1111</CIPHER><VERSION>1.0</VERSION><PRINCIPAL>YMRJGEQZCIGVSPJGD8MJYDH2QR9-ITGJ7RJW9-7RH8JEOF2RD3HHOHO9UC8FDFPY</PRINCIPAL><TOKEN>LIRRX7D-FLGFDZNU3J0OQKCLILQB5XIOS3XL_X1EA5BEOF2RD3HHOHO9UC8FDFPY</TOKEN><SIGNATURE>HTPIRIXVSEXZO7GUFY6AF0+7EX7W9PPE/BTJDZ8QMIC=</SIGNATURE></DJANGOAUTHTOKEN></DJANGOAUTHTOKENS>
 at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.6.6.Final.jar:?]
v5702291716c80bc7fc2f7679-59d12ec5234694940a248fa63f7ae9de-748-com.django.acme.service.message.RefreshMessage-true-false
v570e4b7c32df054416ff1d67-2b54ed0d78fdaaf92c3298664c78cc42-220-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:36:57,926] 1778130199 WARN  [proxy-handler-worker-28] com.django.taas.auth.handler.RecipientHandler - in messageRecieved inboundChannel was closed ignoring setting of channel ops.[id: 0xd019d385, /10.102.11.54:52884 => us0101ame-vip001/10.101.10.80:8080] RECEIVED: DefaultHttpResponse(chunked: false) HTTP/1.1 200 OK Content-Type: application/x-protobuf;charset=ISO-8859-1 Content-Language: en-US Content-Length: 170 Date: Wed, 13 Apr 2016 17:36:56 GMT Server: us0101ame015, Connection Id = [id: 0xc1411b6c, /185.46.137.5:51988 => /199.83.169.114:8080] RECEIVED: DefaultHttpRequest(chunked: false) POST /acme/sync/v1/99fe978441f7905f22d5921895dcc553 HTTP/1.1 Host: acme.django.me Accept: */* Accept-Encoding: deflate, gzip DjangoMe-TaskId: 41 Django-Cipher-Name: DJANGO1111 Django-Cipher-Version: 1.0 Django-Auth-Token: <DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>RZl9s8YzO-1gKr0V2TA9IQ</Principal><Token>w99--_3I-vWupZVzY9gtqaPLTassqsUgHiDdc29NhILeOF2RD3HHoHO9uc8FDfPy</Token><Signature>3beUbUTaYWyCOOsXQ9zVgKtkYI0DiXFqEldzTo32TX4=</Signature><AppId>5KD-PXR_bovYufXc6Es0QQ</AppId></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>TBn94s7eI-nQBpgboOg1XyayPAA_Rtr4SMKRCjVwdNveOF2RD3HHoHO9uc8FDfPy</Principal><Token>w99--_3I-vWupZVzY9gtqaPLTassqsUgHiDdc29NhILeOF2RD3HHoHO9uc8FDfPy</Token><Signature>3pRcD9sL+y+si6M5KIqGEcCArgQaDkJ+6UkL5vhMG9Y=</Signature><AppId>5KD-PXR_bovYufXc6Es0QQ</AppId></DjangoAuthToken></DjangoAuthTokens> Django-Body-Encrypted: none Django-Body-Compressed: none Django-Digest: zq3Ogt7DwAXg/S6/ZldBzw9/sQ4= Content-Type: application/x-protobuf X-Forwarded-For: 185.46.137.5 Content-Length: 120 X-DjangoAuth-Username: 99fe978441f7905f22d5921895dcc553 X-DjangoAuth-AccountId: 2405360891 X-DjangoAuth-AppId: djangosocial
v5709a904c4fd1049eec724b0-4727ced9772724aa3da7325db8588f8c-567-com.django.acme.service.message.RefreshMessage-true-false
v570c6206c4afd121cfebf351-f87d6cbf5f8e4425536aeaab9ee7d8e6-975-com.django.acme.service.message.RefreshMessage-true-false
 at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.6.6.Final.jar:?]
 at com.django.taas.auth.handler.codec.http.HttpDjangoRequestDecoder.createMessage(HttpDjangoRequestDecoder.java:54) ~[authConsumer.jar:?]
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-416-com.django.acme.service.message.RefreshMessage-true-false
 at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.6.6.Final.jar:?]
w56fff4b02ab586117f929e73-4e9f8a5c1d176425f72457be00d23cd1-7441-com.django.acme.service.message.RefreshMessage-true-false
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-446-com.django.acme.service.message.RefreshMessage-true-false
 at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) ~[netty-3.6.6.Final.jar:?]
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-390-com.django.acme.service.message.RefreshMessage-true-false
   }
w56fff4b02ab586117f929e73-4e9f8a5c1d176425f72457be00d23cd1-7410-com.django.acme.service.message.RefreshMessage-true-false
v570adb5dc073c74633436f4b-1aae75e182e32a1140d220237474336e-420-com.django.acme.service.message.RefreshMessage-true-false

v57075ccaf6bf86cd677950f8-a6ae12ef1e7a7bb5169e6bb763f567da-280-com.django.acme.service.message.RefreshMessage-true-false
[2016-04-13T17:49:23,009] 1778875282 INFO  [client-handler-worker-40] com.django.taas.auth.consumer.lib.service.DefaultAuthConsumerService - Digest calculation message: POST/acme/sync/v1/5cf5bcebeb3b032bd98521cafb9ad1bddjango-auth-token<DjangoAuthTokens xmlns="com:django:util:crypto:auth:jaxb" xmlns:ns2="com:django:util:crypto:jaxb:v1:authrsp" xmlns:ns3="service:django:ts:1"><DjangoAuthToken><Type>djangoAccount</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>vZIm4GhQh5XETEyrZ_Qw-Q</Principal><Token>9orABVUCCzMIcl9Q7hyKLpx5pWon-mO68rFKDXGOUvreOF2RD3HHoHO9uc8FDfPy</Token><Signature>3QrXOm+3xBC7ELbnOhGd9jTuRTegBvrs3BIFuIP5Qeg=</Signature></DjangoAuthToken><DjangoAuthToken><Type>djangoDevice</Type><Cipher>DJANGO1111</Cipher><Version>1.0</Version><Principal>mV7EuzesBlPG8ouaaYjOeYznf1hM-CVLW_cVBt5jf4XeOF2RD3HHoHO9uc8FDfPy</Principal><Token>9orABVUCCzMIcl9Q7hyKLpx5pWon-mO68rFKDXGOUvreOF2RD3HHoHO9uc8FDfPy</Token><Signature>NWNpDzXst2xXr3TGmyrgQ2/zqkhPRPJDsbOktgZafgM=</Signature></DjangoAuthToken></DjangoAuthTokens>django-body-compressednonedjango-body-encryptednonedjango-cipher-nameDJANGO1111django-cipher-version1.0' >> $FILENAME
  let COUNTER=COUNTER+1
done
